# Generated by Django 5.0.6 on 2024-06-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12)),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('demurrage', models.DateField(null=True)),
                ('cavalo_entrada', models.CharField(max_length=8)),
                ('cavalo_saida', models.CharField(blank=True, max_length=8)),
                ('prancha_entrada', models.CharField(max_length=8)),
                ('prancha_saida', models.CharField(blank=True, max_length=8)),
                ('lacre', models.CharField(max_length=5)),
                ('origem', models.CharField(max_length=25)),
                ('destino', models.CharField(blank=True, max_length=25)),
                ('avaria', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Container_Aurora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Localização',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localização', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Porto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preenchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Nota_Fiscal', models.CharField(max_length=20)),
                ('data_Lançamento_NF', models.DateTimeField(blank=True)),
                ('numero_DI', models.CharField(blank=True, max_length=30)),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('avaria', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente')),
                ('container_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carga_entrada_set', to='main.container')),
                ('container_saida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='carga_saida_set', to='main.container')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='Desunitição_e_Unitização',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_de_caixas_ou_volume', models.CharField(max_length=5)),
                ('lacre_Original', models.CharField(max_length=10, unique=True)),
                ('lacre_Aurora', models.CharField(max_length=10, unique=True)),
                ('data_Deslacre', models.DateTimeField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.carga')),
                ('conferente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.conferente')),
                ('container_Cedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.container_aurora')),
                ('container_Origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='localização',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.localização'),
        ),
        migrations.AddField(
            model_name='container',
            name='motorista_Entrada',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='motorista_entrada_set', to='main.motorista'),
        ),
        migrations.AddField(
            model_name='container',
            name='motorista_Saida',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='motorista_saida_set', to='main.motorista'),
        ),
        migrations.AddField(
            model_name='container',
            name='porto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.porto'),
        ),
        migrations.AddField(
            model_name='container',
            name='preenchimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.preenchimento'),
        ),
        migrations.AddField(
            model_name='container',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tipocontainer'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transportadora'),
        ),
        migrations.AddField(
            model_name='container',
            name='transportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transportadora'),
        ),
    ]
