# Generated by Django 5.0.6 on 2024-07-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tipoavaria_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoavaria',
            old_name='nome',
            new_name='avaria',
        ),
    ]
