# Generated by Django 5.0.6 on 2024-07-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_carga_container_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField()),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('cavalo_saida', models.CharField(max_length=8)),
                ('cavalo_retorno', models.CharField(blank=True, max_length=8, null=True)),
                ('prancha_saida', models.CharField(max_length=8)),
                ('prancha_retorno', models.CharField(blank=True, max_length=8, null=True)),
                ('origem', models.CharField(max_length=25)),
                ('destino', models.CharField(blank=True, max_length=25)),
                ('avaria', models.ManyToManyField(blank=True, to='main.tipoavaria')),
                ('lacre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lacre')),
                ('motorista_retorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cedido_motorista_retorno', to='main.motorista')),
                ('motorista_saida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cedido_motorista_saida', to='main.motorista')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.container_aurora')),
                ('preenchimento_retorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cedido_preenchimento_retorno', to='main.preenchimento')),
                ('preenchimento_saida', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cedido_preenchimento_saida', to='main.preenchimento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tipocontainer')),
                ('transportador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transportadora')),
            ],
        ),
    ]
