# Generated by Django 5.0.6 on 2024-07-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedido',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
