# Generated by Django 5.0.6 on 2024-07-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cedido_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='quantidade_de_caixas_ou_volume',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='lacre',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='desunitição_e_unitização',
            name='lacre_Aurora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lacre'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
